package com.cyberlink.cosmetic.event;

import org.apache.commons.lang.StringUtils;

public enum EventType {

    USER_ACCOUNT_CREATED, USER_ACCOUNT_DELETED, USER_PREFERENCE_UPDATED, USER_DISPLAY_NAME_UPDATED, USER_USER_DELETED, USER_AVATAR_UPDATED, USER_COVERART_UPDATED, USER_STATUS_UPDATED,

    CONTACT_CONTACT_SYNCED, CONTACT_CONTACT_DELETED, CONTACT_CONTACT_CLEANED,

    INVITE_FRIEND_DENIED, INVITE_CONTACT_CANCELED, INVITE_FRIEND_CANCELED, INVITE_FRIEND_ACCEPTED, INVITE_CONTACT_CREATED, INVITE_FRIEND_CREATED, INVITE_URL_UPDATED, INVITE_CONTACT_DELETED, INVITE_FRIEND_DELETED,

    SUGGESTION_SUGGESTION_CREATED, SUGGESTION_SUGGESTION_DELETED,

    GROUP_GROUP_CREATED, GROUP_GROUP_UPDATED, GROUP_GROUP_DISABLED, GROUP_GROUP_HIDED, GROUP_MEMBER_LEAVED, GROUP_MEMBER_CREATED, GROUP_MEMBER_DELETED, GROUP_ALBUM_CREATED, GROUP_ALBUM_UPDATED, GROUP_ALBUM_DELETED, GROUP_ALBUM_AVATAR_UPDATED, GROUP_MEDIA_DELETED, GROUP_MEDIA_CREATED, GROUP_COMMENT_CREATED, GROUP_COMMENT_UPDATED, GROUP_COMMENT_DELETED, GROUP_GROUP_SHOWED, GROUP_GROUP_ENABLED,

    CHAT_ALBUM_CREATED, CHAT_ALBUM_UPDATED, CHAT_ALBUM_DELETED, CHAT_MEDIA_CREATED, CHAT_MEDIA_DELETED, CHAT_COMMENT_CREATED, CHAT_COMMENT_UPDATED, CHAT_COMMENT_DELETED, CHAT_MESSAGE_DELETED, CHAT_MESSAGE_RECALLED,

    STICKER_USER_PACK_CREATED,

    BACKUP_PRODUCT_ALBUM_CREATED, BACKUP_ALBUM_CREATED, BACKUP_ALBUM_UPDATED, BACKUP_ALBUM_DELETED, BACKUP_MEDIA_CREATED, BACKUP_MEDIA_DELETED, BACKUP_COMMENT_CREATED, BACKUP_COMMENT_UPDATED, BACKUP_COMMENT_DELETED,

    FRIEND_FRIEND_CREATED, FRIEND_FRIEND_DELETED, FRIEND_FRIEND_HIDED, FRIEND_FRIEND_UNHIDED, FRIEND_FRIEND_BLOCKED, FRIEND_FRIEND_UNBLOCKED, FRIEND_FRIEND_BROKE_UP, FRIEND_NICKNAME_UPDATED, FRIEND_FRIEND_SHOWED, FRIEND_FRIEND_UNBROKE_UP, FRIEND_MESSAGE_DELETED,

    MEDIA_UPLOAD_COMPLETED, MEDIA_MEDIA_DELETED, MEDIA_COPY_COMPLETED, MEDIA_MEDIA_CREATED,

    MEDIA_COMMENT_CREATED, MEDIA_COMMENT_UPDATED, MEDIA_COMMENT_DELETED,

    MEDIA_ALBUM_CREATED, MEDIA_ALBUM_UPDATED, MEDIA_ALBUM_DELETED;

    private final String typeName;

    private EventType() {
        final String l = StringUtils.lowerCase(name());
        this.typeName = StringUtils.replace(l, "_", ".");
    }

    public String getTypeName() {
        return typeName;
    }
}
